---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.docker
    - marklee77.mariadb

- hosts: all
  gather_facts: True
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: python-mysqldb
        state: latest
        update_cache: yes
        cache_valid_time: 600

