---
- name: ensure keystone packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-keystoneclient
    - python-mysqldb
    - keystone

- name: ensure keystone is started and enabled
  service: 
    name: keystone
    state: started 
    enabled: yes

- name: ensure keystone is properly shut down for dockerized deployments
  service:
    name: keystone
    state: stopped
    enabled: yes
  when: keystone_dockerize_context is defined
