---
- name: ensure keystone database is present
  mysql_db:
    login_host: "{{ keystone_mysql_host }}"
    login_port: "{{ keystone_mysql_port }}"
    login_user: root
    login_password: "{{keystone_mysql_root_password }}"
    name: keystone
  register: create_keystone_db

- name: ensure keystone database user is present
  mysql_user:
    login_host: "{{ keystone_mysql_host }}"
    login_port: "{{ keystone_mysql_port }}"
    login_user: root
    login_password: "{{keystone_mysql_root_password }}"
    name: keystone
    host: "{{ item }}"
    password: "{{ keystone_mysql_keystone_password }}"
    priv: keystone.*:ALL
  with_items:
    - localhost
    - "%"

- include: docker.yml
  when: keystone_dockerized_deployment

- include: install.yml
  when: not keystone_dockerized_deployment

- include: offline_configuration.yml
  when: not keystone_dockerized_deployment 

- name: wait until keystone service is ready
  wait_for:
    delay: 1
    host: "{{ keystone_identity_endpoint_host }}"
    port: 35357
    state: started

- name: create admin tenant
  keystone_user:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: create admin user
  keystone_user:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ keystone_identity_admin_password }}"

- name: create admin role and associate it with admin user
  keystone_user:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: associate _member_ role with the admin user
  keystone_user:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: create service tenant
  keystone_user:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

- name: add keystone endpoint information
  keystone_service:
    endpoint: "{{ keystone_identity_admin_url }}"
    token: "{{ keystone_identity_admin_token }}"
    region: "{{ keystone_identity_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ keystone_identity_public_url }}"
    internal_url: "{{ keystone_identity_internal_url }}"
    admin_url: "{{ keystone_identity_admin_url }}"

