---
- include: mysql.yml

- include: docker.yml
  when: keystone_dockerized_deployment

- include: install.yml
  when: not keystone_dockerized_deployment

- include: offline_configuration.yml
  when: not keystone_dockerized_deployment 

- include: keystone.yml
