---
# FIXME: for security we assume root login requires direct login access to mysql
# node, needs delegate_to for non-centralized deployments.

- name: ensure keystone database is present
  mysql_db:
    login_host: 127.0.0.1
    login_port: "{{ keystone_mysql_port }}"
    login_user: root
    login_password: "{{ keystone_mysql_root_password }}"
    name: keystone
  register: create_keystone_db

- name: ensure keystone database user is present
  mysql_user:
    login_host: 127.0.0.1
    login_port: "{{ keystone_mysql_port }}"
    login_user: root
    login_password: "{{ keystone_mysql_root_password }}"
    name: keystone
    host: "{{ item }}"
    password: "{{ keystone_mysql_keystone_password }}"
    priv: keystone.*:ALL
  with_items:
    - localhost
    - "%"
